export default {
    refreshTime: 5,
    hideRefresher: false,
    useShortcut: false,
    hideNotice: true,
    fixHeader: true,
    hideAvatar: false,
    hideMedia: false,
    hideModified: false,
    hideSideMenu: false,
    myImage: '',
    blockRatedown: false,
    blockKeyword: [],
    blockUser: [],
    blockEmoticon: {},
    userMemo: {},
    useAutoRemoverTest: true,
    autoRemoveUser: [],
    autoRemoveKeyword: [],
    category: {},
    imageDownloaderFileName: '%title%',
};
