name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[version]') }}
    steps:
      - name: Get Version
        id: get-version
        run: |
          message="${{ github.event.head_commit.message }}"
          version="${message//\[version\] /}"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: lts/*
          cache: npm

      - name: Install packages
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Create GitHub Release
        id: release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          files: |
            ./dist/ArcaRefresher.user.js
            ./dist/ArcaRefresher.meta.js
            ./dist/ArcaRefresher.user.js.LICENSE.txt
